[package]
name = "problem_02"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "bin/server.rs"

[dependencies]
atoi = "0.3.2"
bytes = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
