# fly.toml app configuration file generated for restless-bush-123 on 2023-04-19T13:36:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-bush-123"
primary_region = "ams"

[experimental]
  auto_rollback = true

[env]
  ECHO_PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 8080
